[Policies] "Customer Connectivity Settings" must be re-named to "Exte…
CustomSDL/sdl_hmi pull request #3
Opened 2017-01-24 07:38 UTC by wolfylambova22

…rnal User Consent Settings"

Fix naming of parameters of CCS

Related issue: APPLINK-30422

2017-01-24 07:39 UTC, wolfylambova22 commented
@OHerasym @dev-gh @AGaliuzov @VProdanov @orhan-mehmedov Please review.

2017-01-24 09:47 UTC, AGaliuzov approved these changes

2017-01-24 09:55 UTC, ghost approved these changes

2017-01-24 10:03 UTC, orhan-mehmedov approved these changes

2017-01-24 12:51 UTC, dev-gh approved these changes

2017-01-24 16:03 UTC, Kozoriz requested changes

2017-01-24 16:03 UTC, Kozoriz commented on app/view/WarningView.js
> -                .checkForCCS3AnimationSupport()
@wolfylambova22 , there is CSS, not "Customer Connectivity Settings ". 
There is mistake, not CCS, must be CSS (Cascading Style Sheets)
Please change to CSS.

2017-01-24 16:03 UTC, Kozoriz commented on app/view/WarningView.js
> -          checkForCCS3AnimationSupport: function() {
@wolfylambova22 , and there is too..

2017-01-26 07:39 UTC, OHerasym approved these changes

2017-01-30 08:03 UTC, wolfylambova22 commented on app/view/WarningView.js
> -          checkForCCS3AnimationSupport: function() {
@Kozoriz Thank you. Fixed in dd9b3142c94eb8faa79193cb50eb95f6147e0d16.

2017-01-30 08:03 UTC, wolfylambova22 commented on app/view/WarningView.js
> -                .checkForCCS3AnimationSupport()
@Kozoriz Fixed in dd9b314.

2017-01-31 08:53 UTC, wolfylambova22 commented
@Kozoriz Please finish review.

2017-02-01 08:10 UTC, Kozoriz commented on app/view/WarningView.js
> +          checkForCCS3AnimationSupport: function() {
@wolfylambova22 , i understand it is not in scope of your task, but can you change CCS to CSS. This is not your mistake (just misstake in code). Can you?

2017-02-01 08:10 UTC, Kozoriz approved these changes

2017-02-01 13:04 UTC, merged