Add support of new GetSystemTime RPC
CustomSDL/sdl_hmi pull request #4
Opened 2017-02-28 09:43 UTC by AKalinich-Luxoft

Added implementation of onSystemTimeReady().
Added onSystemTimeReady notification right after onReady().
Added implemetation of GetSystemTime() to response on approriate SDL request.

Related tasks : [APPLINK-29396](https://adc.luxoft.com/jira/browse/APPLINK-29396), [APPLINK-29386](https://adc.luxoft.com/jira/browse/APPLINK-29386)

2017-02-28 10:11 UTC, OHerasym approved these changes

2017-02-28 14:39 UTC, pvvasilev approved these changes

2017-02-28 14:39 UTC, pvvasilev commented on ffw/BasicCommunicationRPC.js
> +       * BasicCommunication should be sunscribed to this notification
@AKalinich-Luxoft typo "subscribed"

2017-03-02 11:25 UTC, wolfylambova22 approved these changes

2017-03-02 15:11 UTC, Kozoriz requested changes

2017-03-02 15:11 UTC, Kozoriz commented on ffw/BasicCommunicationRPC.js
> +        }
@AKalinich-Luxoft , can we use : 

> var tzo = -current_time.getTimezoneOffset();
> var tz_hour = tzo / 60;
> var tz_min = tzo % 60; 

?

2017-03-02 15:55 UTC, AByzhynar approved these changes

2017-03-02 15:56 UTC, AByzhynar commented
@AKalinich-Luxoft Sorry I don't know JS

2017-03-03 10:24 UTC, AKalinich-Luxoft commented on ffw/BasicCommunicationRPC.js
> +       * BasicCommunication should be sunscribed to this notification
@pvvasilev, thanks, fixed in [43c9ff7](https://github.com/CustomSDL/sdl_hmi/pull/4/commits/43c9ff7ae8ada9211f2ed5ef1b79da294f8478ed)

2017-03-03 10:29 UTC, AKalinich-Luxoft commented on ffw/BasicCommunicationRPC.js
> +        }
@Kozoriz, yes, it's good idea. But there were some clarifications for this function and there is no need to calculate this fields anymore (see [APPLINK-33109](https://adc.luxoft.com/jira/browse/APPLINK-33109)). I've changed it in [43c9ff7](https://github.com/CustomSDL/sdl_hmi/pull/4/commits/43c9ff7ae8ada9211f2ed5ef1b79da294f8478ed)

2017-03-03 10:37 UTC, anosach-luxoft approved these changes

2017-03-03 12:13 UTC, Kozoriz approved these changes

2017-03-03 12:14 UTC, merged